#!/usr/bin/python
import os, os.path, commands
import formatter, StringIO

def reflow(s):
    out=StringIO.StringIO()
    w=formatter.DumbWriter(out)
    for para in s.split('\n\n'):
	if para[:1]==' ':
	    w.send_literal_data(para)
	else:
	    w.send_flowing_data(para)
	    w.send_literal_data('\n')
	w.send_paragraph(1)

    l=[]
    for line in out.getvalue().split('\n'):
	if line=='':
	    l.append(' .')
	else:
	    l.append(' '+line)
    while l and l[-1]==' .':
	del l[-1]
    return '\n'.join(l)


class CmdDict:
    def __init__(self, setup=None):
	self.setup=setup

    def handle_setup(self, cmd):
	assert self.setup
	return self.handle_shell('python %s %s'%(self.setup, cmd))

    def handle_extract_setup_var(self, var):
	"""Extract a variable from a comment inside the setup file."""
	assert self.setup
	f=open(self.setup)
	start="#%s:" % var
	for line in f.xreadlines():
	    line=line.strip()
	    if line.startswith(start):
		line=line[len(start):].strip()
		return line
	raise 'No special variable %s in setup file %s' \
	      % (repr(var), self.setup)

    def handle_shell(self, cmd):
	status, output = commands.getstatusoutput(cmd)
	if status:
	    raise 'Command %s failed with exit status %d.' \
		  % (repr(cmd), status)
	return output

    def __getitem__(self, s):
	first, rest = s.split(None, 1)
	f=getattr(self, 'handle_'+first.replace('-', '_'))
	return f(rest)

otherpackage = """
Package: %(setup --name)s
Section: %(extract-setup-var debian-section)s
Architecture: all
Depends: ${python:Depends}, python-twisted-core, python-twisted-mail, python-ldaptor (>= 0.0.25), postfix (>= 0.0.20010329.SNAPSHOT), python-zopeinterface, adduser, python-openssl
Suggests: courier-imap-ssl | courier-ssl, slapd
Description: %(setup --description)s
"""

filename = 'setup.py'

print """\
Source: %(shell dpkg-parsechangelog|sed -n 's/^Source: //p')s
Section: %(extract-setup-var debian-section)s
Priority: optional
Maintainer: %(setup --contact)s <%(setup --contact-email)s>
Standards-Version: 3.7.2
Build-Depends: cdbs (>= 0.4.8.1), debhelper (>= 4.1.0), python-dev, python-support
""" % CmdDict(filename)

c=CmdDict(filename)
print otherpackage.strip() % c
print reflow('%(setup --long-description)s' % c)
print
